#!/bin/bash

# Ensure that this script is sourced, not executed
# Note that if the script was executed, we're running inside bash!
if [[ -n $BASH_VERSION ]] && [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    >&2 echo "Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.
"
    exit 1
fi

# Determine the directory containing this script
if [[ -n $BASH_VERSION ]]; then
    _SCRIPT_LOCATION=${BASH_SOURCE[0]}
elif [[ -n $ZSH_VERSION ]]; then
    _SCRIPT_LOCATION=${funcstack[1]}
else
    echo "Only bash and zsh are supported"
    return 1
fi
_THIS_DIR=$(dirname "$_SCRIPT_LOCATION")

if [[ -n "$WMT_ENV" ]]; then
    _NEW_ENV=$("$_THIS_DIR/wmt-deactivate")
    if (( $? == 0 )); then
        eval "$_NEW_ENV"
        if [[ -n "$WMT_OLD_PS1" ]]; then
            PS1="$WMT_OLD_PS1"
            unset WMT_OLD_PS1
        fi
    else
        return $?
    fi
    unset WMT_ENV
fi

# http://stackoverflow.com/a/21188136/161801
get_abs_filename() {
    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

FILE=$(get_abs_filename "$_THIS_DIR")
#WMT_ENV=$(basename $(dirname $FILE))
WMT_ENV=$(dirname $FILE)

_NEW_ENV=$("$_THIS_DIR/wmt-activate" "$_THIS_DIR/../etc/wmt.cfg" \
  "--prepend-base=$_THIS_DIR/.." \
  "--prepend-base=$_THIS_DIR/../local")
if (( $? == 0 )); then
    eval "$_NEW_ENV"
    if [[ -n "$WMT_CHANGE_PS1" ]]; then
        WMT_OLD_PS1="$PS1"
        PS1="(\e[35;1m\]csdms-$WMT_ENV\e[0m\])\n$PS1"
    fi
    export WMT_ENV
else
    return $?
fi

if [[ -n $BASH_VERSION ]]; then
    hash -r
elif [[ -n $ZSH_VERSION ]]; then
    rehash
else
    echo "Only bash and zsh are supported"
    return 1
fi
